name = "hexdocs_offline"
version = "1.0.8"

description = "Downloads an offline version of the hexdocs of your projects dependencies to a local folder"
licences = ["Apache-2.0"]

repository = { type = "github", user = "daniellionel01", repo = "hexdocs_offline" }

internal_modules = ["hexdocs_offline/internal", "hexdocs_offline/internal/*"]

[dependencies]
tom = ">= 2.0.0 and < 3.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
nakai = ">= 1.1.1 and < 2.0.0"
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
child_process = ">= 1.2.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
