name = "hexdocs_offline"
version = "0.0.1"

description = "Downloads an offline version of the hexdocs of your projects dependencies to a local folder"
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_httpc = ">= 3.0.0 and < 4.0.0"
gleam_http = ">= 3.7.1 and < 4.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
tom = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
